# Generated by Django 3.2.8 on 2021-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[(1, 'faible'), (2, 'moyenne'), (3, 'élevée')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(1, 'a faire'), (2, 'en cours'), (3, 'terminé')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[(1, 'bug'), (2, 'amélioration'), (3, 'tâche')], default=1, max_length=1),
        ),
    ]
