# Generated by Django 3.2.8 on 2021-10-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0003_contributor_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['user_id']},
        ),
    ]
