# Generated by Django 3.2.8 on 2021-10-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_author_user_id'),
        ('contributor', '0004_alter_contributor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={},
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='project.project'),
        ),
    ]
