# Generated by Django 3.2.8 on 2021-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_auto_20211026_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[(1, 'pilote'), (2, 'manager'), (3, 'mécano'), (4, 'chef Mécano'), (5, 'data anlyst'), (6, 'testeur')], default=1, max_length=1),
        ),
    ]
