# Generated by Django 3.2.8 on 2021-10-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0006_alter_contributor_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
