# Generated by Django 3.2.8 on 2021-10-28 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20211026_1746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_remove_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.issue'),
        ),
    ]
